import "./globals.css";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Layout } from "@/components/layout/Layout";
import { AuthProvider } from "@/components/authentication/SessionProvider";
import { SnackBarContextProvider } from "@/components/common/snackbar/SnackbarContext";

export const metadata: Metadata = {
  title: "Hello Condo (Admin)",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
        <link
          rel="icon"
          href={process.env.NEXT_PUBLIC_ASSETS_URL + "images/Logo.svg"}
          sizes="any"
        />
        <SnackBarContextProvider>
          <AuthProvider session={session}>
            <Layout>{children}</Layout>
          </AuthProvider>
        </SnackBarContextProvider>
      </body>
    </html>
  );
}
